In [63]:
import numpy as np

mat = np.array([[3,5,7,4,6],
               [5,3,1,5,3],
               [2,8,3,1,4],
               [4,5,7,2,3],
               [3,1,3,2,0]])
ans = []

In [64]:
def BFS(mat, visited, ans, init = ()):
    queue = []
    if len(init) == 0:
        queue.append((mat[0][0], 0, 0, 0)) 
    else:
        queue.append(init)
    while len(queue) != 0:
        if (queue[0][1] + queue[0][0] < x) and (visited[(queue[0][1] + queue[0][0])][queue[0][2]] == False):
            queue.append((mat[(queue[0][1] + queue[0][0])][queue[0][2]], queue[0][1] + queue[0][0], queue[0][2], queue[0][3] + 1))
            visited[(queue[0][1] + queue[0][0])][queue[0][2]] = True
            if (queue[0][1] + queue[0][0] == x-1) and (queue[0][2] == x-1):
                ans.append(queue[0][3]+1)

        if (queue[0][1] - queue[0][0] >= 0) and (visited[(queue[0][1] - queue[0][0])][queue[0][2]] == False):
            queue.append((mat[(queue[0][1] - queue[0][0])][queue[0][2]], queue[0][1] - queue[0][0], queue[0][2], queue[0][3] + 1))
            visited[(queue[0][1] - queue[0][0])][queue[0][2]] = True
            if (queue[0][1] - queue[0][0] == x-1) and (queue[0][2] == x-1):
                ans.append(queue[0][3]+1)                

        if (queue[0][2] + queue[0][0] < y) and (visited[queue[0][1]][(queue[0][2] + queue[0][0])] == False):
            queue.append((mat[queue[0][1]][(queue[0][2] + queue[0][0])], queue[0][1], queue[0][2] + queue[0][0], queue[0][3] + 1))
            visited[queue[0][1]][(queue[0][2] + queue[0][0])] = True
            if (queue[0][1] == x-1) and (queue[0][2] + queue[0][0] == x-1):
                ans.append(queue[0][3]+1)                    

        if (queue[0][2] - queue[0][0] >= 0) and (visited[queue[0][1]][(queue[0][2] - queue[0][0])] == False):  
            queue.append((mat[queue[0][1]][(queue[0][2] - queue[0][0])], queue[0][1], queue[0][2] - queue[0][0], queue[0][3] + 1))
            visited[queue[0][1]][(queue[0][2] - queue[0][0])] = True
            if (queue[0][1] == x-1) and (queue[0][2] - queue[0][0] == x-1):
                ans.append(queue[0][3]+1)
        queue.pop(0)


x,y = mat.shape
visited = np.full((x,y), False, dtype=bool)
BFS(mat, visited, ans)
print(mat)
if(len(ans) == 0):
    print("No Solution")
else:
    print(min(ans))


[[3 5 7 4 6]
 [5 3 1 5 3]
 [2 8 3 1 4]
 [4 5 7 2 3]
 [3 1 3 2 0]]
8
